dataset: meta-domain-net
train_set_args: 
  root: /srv/home/zxu444/datasets/domainNet/sketch_split
  split: meta-train
  size: 224           
  transform: dinov2
  n_batch: 200
  n_episode: 1
  n_way: 15
  n_shot: 1
  n_query: 9
  deterministic: True  # whether set images in dataset to be deterministic in each epoch
val_set_args:
  root: /srv/home/zxu444/datasets/domainNet/sketch_split
  split: meta-val
  size: 224           
  transform: make_classification_eval_transform
  n_batch: 200
  n_episode: 1
  n_way: 15
  n_shot: 1
  n_query: 10
  deterministic: True  # whether set images in dataset to be deterministic in each epoch


encoder: torchvision_vit_b_32
stdFT: True



classifier: fs-centroid
classifier_args:
  temp: 10.
  learn_temp: True

optimizer: sgd
optimizer_args:
  lr: 0.01
  momentum: 0.9
  weight_decay: 5.e-6


########### M,m trend
save_path: ./save/torchvision/domain-net/stdFT


save_epoch: 5
V: 1
n_epochs: 10

