dataset: meta-domain-net
test_set_args:
  root: /srv/home/zxu444/datasets/domainNet/sketch_split
  split: meta-test
  size: 224                 
  transform: make_classification_eval_transform
  n_batch: 150
  n_episode: 2
  n_way: 15
  n_shot: 1
  n_query: 15


encoder: dinov2_vitb14

path: ./save/dinov2/mixed-set/Mm_trend/meta-mixed-set_dinov2_vitb14_fs-centroid_15y2s18q_300m_100M
ckpt: max-va.pth
# ckpt: epoch-last.pth


classifier: fs-centroid
classifier_args:
  temp: 10.

V: 1
n_epochs: 10
