dataset: meta-mini-imagenet
train_set_args:
  split: meta-train
  size: 224           # added for CLIP
  transform: clip
  n_batch: 200
  n_episode: 1
  n_way: 15
  n_shot: 1
  n_query: 9
  deterministic: True  # whether set images in dataset to be deterministic in each epoch
val_set_args:
  split: meta-val
  size: 224           # added for CLIP
  transform: clip
  n_batch: 200
  n_episode: 1
  n_way: 15
  n_shot: 1
  n_query: 10
  deterministic: True  # whether set images in dataset to be deterministic in each epoch

encoder: clip_RN50
stdFT: True

# path: ./save/clip/meta-mini-imagenet_RN50_fs-centroid_5y1s_finetune_clip_old
# ckpt: max-va.pth

classifier: fs-centroid
classifier_args:
  temp: 10.
  learn_temp: True

optimizer: sgd
optimizer_args:
  lr: 1.e-4 # 0.001
  momentum: 0.99
  weight_decay: 0 # 5.e-4

save_path: ./save/clip/mini-imagenet/stdFT


V: 1
n_epochs: 30
