dataset: meta-mini-imagenet
train_set_args: 
  split: meta-train
  size: 224           # added for ViT
  transform: clip
  n_batch: 200
  n_episode: 1
  n_way: 15
  n_shot: 1
  n_query: 9
  deterministic: True  # whether set images in dataset to be deterministic in each epoch
val_set_args:
  split: meta-val
  size: 224           # added for ViT
  transform: clip
  n_batch: 200
  n_episode: 1
  n_way: 15
  n_shot: 1
  n_query: 10
  deterministic: True  # whether set images in dataset to be deterministic in each epoch


encoder: clip_ViT-B32

LP: False

path: ./save/clip/mini-imagenet/stdFT/meta-mini-imagenet_clip_ViT-B32_lp_logistic_15y1s_150m_200M
ckpt: lp_epoch-5.pth
LP_FT: True


classifier: fs-centroid
classifier_args:
  temp: 10.
  learn_temp: True

lp_optimizer: sgd
lp_optimizer_args:
  lr: 1.
  schedule: step
  decay_rate: 0.1
  decay_epochs:
    - 60
    - 80
  momentum: 0.9
  weight_decay: 0
lp_n_epochs: 5

optimizer: sgd
optimizer_args:
  lr: 1.e-6 # 0.001
  schedule: step
  decay_rate: 0.1
  decay_epochs:
    - 5
  momentum: 0.9
  weight_decay: 5.e-6
n_epochs: 10

# rm_path: True
save_path: ./save/clip/mini-imagenet/stdFT

save_epoch: 1
V: 1
