dataset: vl-meta-tiered-imagenet
train_set_args: 
  root: /srv/home/zxu444/datasets/tiered-imagenet/tiered_imagenet
  split: meta-train
  size: 224           
  transform: clip
  n_batch: 20
  n_episode: 1
  n_way: 50
  # n_query: 15
  n_query: 1 # for ConLoss
  # deterministic: True  # whether set images in dataset to be deterministic in each epoch
val_set_args:
  root: /srv/home/zxu444/datasets/tiered-imagenet/tiered_imagenet
  split: meta-val
  size: 224          
  transform: clip
  n_batch: 20
  n_episode: 1
  n_way: 50
  # n_query: 2
  n_query: 1 # for ConLoss
  # deterministic: True  # whether set images in dataset to be deterministic in each epoch
test_set_args:
  root: /srv/home/zxu444/datasets/tiered-imagenet/tiered_imagenet
  split: meta-test
  size: 224                 # add for clip
  transform: clip
  n_batch: 15
  n_episode: 1
  n_way: 50
  # n_query: 15
  n_query: 1 # for ConLoss
  # deterministic: True

### only for test
path: ./save/VL/tiered-imagenet/ConLoss/vl-meta-tiered-imagenet_ViT-B32_fs-centroid_50y_1q_20M_1e-07lr
ckpt_name: vl-meta-tiered-imagenet_ViT-B32_fs-centroid_50y_1q_20M_1e-07lr
ckpt: max-va.pth
encoder: ViT-B32

### load model
# path: ./save/VL/tiered-imagenet/vl-meta-tiered-imagenet_ViT-B32_fs-centroid_100y_15q_200M
# ckpt: max-va.pth
# ckpt: epoch-last.pth

###
classifier: fs-centroid
classifier_args:
  temp: 10.

optimizer: sgd
optimizer_args:
  lr: 1.e-8 # 0.001
  momentum: 0.9
  weight_decay: 0 # 5.e-6

save_path: ./save/VL/tiered-imagenet

save_epoch: 1
n_epochs: 30
# start_epoch_from: 160