dataset: meta-tiered-imagenet
train_set_args: 
  split: meta-train
  size: 224           
  transform: mocov3
  val_transform: mocov3
  n_batch: 200
  n_episode: 1
  n_way: 15
  n_shot: 1
  n_query: 9
  deterministic: True  # whether set images in dataset to be deterministic in each epoch
val_set_args:
  split: meta-val
  size: 224           
  transform: flip
  val_transform: flip
  n_batch: 200
  n_episode: 1
  n_way: 15
  n_shot: 1
  n_query: 10
  deterministic: True  # whether set images in dataset to be deterministic in each epoch


encoder: mocov3_vit
encoder_args: 
  # arch: vit_small
  # ckpt_path: ../pretrained_model/mocov3/vit-s-300ep.pth.tar
  arch: vit_base
  ckpt_path: ../pretrained_model/mocov3/vit-b-300ep.pth.tar



# path: ./save/task_samples/task5000/meta-mini-imagenet_ViT-B32_fs-centroid_5y25s_1000size
# path: ./save/tiered-imagenet/Mm_trend/meta-tiered-imagenet_ViT-B32_fs-centroid_15y1s_150m_600M
# ckpt: epoch-last.pth
# start_epoch_from: 10

classifier: fs-centroid
classifier_args:
  temp: 10.
  learn_temp: True

optimizer: sgd
optimizer_args:
  lr: 1.e-5
  momentum: 0.9
  weight_decay: 0


########### M,m trend
# save_path: ./save/mocov3/tiered-imagenet/Mm_trend

save_path: ./save/mocov3/tiered-imagenet/sample_complex

save_epoch: 5
V: 1
n_epochs: 10

