dataset: meta-tiered-imagenet
test_set_args:
  split: meta-test
  size: 224                 # add for clip
  transform: clip
  n_batch: 100
  n_episode: 2
  n_way: 15
  n_shot: 1
  n_query: 15


encoder: clip_ViT-B32
# encoder: clip_RN50


path: ./save/clip/tiered-imagenet/meta-tiered-imagenet_clip_ViT-B32_fs-centroid_15y2s18q_300m_100M
ckpt: max-va.pth
# ckpt: epoch-last.pth


classifier: fs-centroid
classifier_args:
  temp: 10.

V: 1
n_epochs: 10