dataset: meta-tiered-imagenet
test_set_args:
  split: meta-test
  size: 224                 # add for clip
  transform: clip
  n_batch: 150
  n_episode: 1
  n_way: 15
  n_shot: 1
  n_query: 15


encoder: clip_ViT-B32
# encoder: clip_RN50

# path: ./save/clip/tiered-imagenet/stdFT/meta-tiered-imagenet_clip_ViT-B32_lp_logistic_15y1s_150m_200M
# path: ./save/clip/tiered-imagenet/stdFT/meta-tiered-imagenet_clip_RN50_lp_logistic_15y1s_150m_200M

path: ./save/clip/tiered-imagenet/limited_class/meta-tiered-imagenet_clip_ViT-B32_fs-centroid_15y1s9q_150m_200Mclass10
ckpt: max-va.pth
# ckpt: epoch-last.pth


classifier: fs-centroid
classifier_args:
  temp: 10.

V: 1
n_epochs: 10