dataset: meta-tiered-imagenet
train_set_args: 
  split: meta-train
  size: 224           # added for ViT
  transform: dinov2
  val_transform: dinov2
  n_batch: 200
  n_episode: 1
  n_way: 15
  n_shot: 1
  n_query: 9
  deterministic: True  # whether set images in dataset to be deterministic in each epoch
val_set_args:
  split: meta-val
  size: 224           # added for ViT
  transform: make_classification_eval_transform
  val_transform: make_classification_eval_transform
  n_batch: 200
  n_episode: 1
  n_way: 15
  n_shot: 1
  n_query: 10
  deterministic: True  # whether set images in dataset to be deterministic in each epoch


encoder: dinov2_vitb14
stdFT: True



classifier: fs-centroid
classifier_args:
  temp: 10.
  learn_temp: True

optimizer: sgd
optimizer_args:
  lr: 0.001
  momentum: 0.9
  weight_decay: 5.e-6


########### M,m trend
save_path: ./save/dinov2/tiered-imagenet/stdFT


save_epoch: 5
V: 1
n_epochs: 10

