dataset: meta-domain-net
train_set_args: 
  root: /srv/home/zxu444/datasets/domainNet/sketch_split
  split: meta-train
  size: 224           # added for ViT
  transform: clip
  n_batch: 200
  n_episode: 1
  n_way: 15
  n_shot: 1
  n_query: 9
  deterministic: True  # whether set images in dataset to be deterministic in each epoch
val_set_args:
  root: /srv/home/zxu444/datasets/domainNet/sketch_split
  split: meta-val
  size: 224           # added for ViT
  transform: clip
  n_batch: 200
  n_episode: 1
  n_way: 15
  n_shot: 1
  n_query: 10
  deterministic: True  # whether set images in dataset to be deterministic in each epoch


encoder: clip_ViT-B32
stdFT: True


# path: ./save/task_samples/task5000/meta-mini-imagenet_ViT-B32_fs-centroid_5y25s_1000size
# path: ./save/clip/meta-mini-imagenet_RN50_fs-centroid_5y1s_finetune_clip
# path: ./save/mini-imagenet/Mm_trend/meta-mini-imagenet_ViT-B32_fs-centroid_15y4s_600m_800M
# ckpt: epoch-10.pth
# start_epoch_from: 10

classifier: fs-centroid
classifier_args:
  temp: 10.
  learn_temp: True

optimizer: sgd
optimizer_args:
  lr: 0.01
  momentum: 0.9
  weight_decay: 5.e-6


########### M,m trend
save_path: ./save/clip/domain-net/stdFT


save_epoch: 5
V: 1
n_epochs: 10

