dataset: meta-domain-net
train_set_args: 
  root: /srv/home/zxu444/datasets/domainNet/sketch_split
  split: meta-train
  size: 224           # added for ViT
  transform: clip
  n_batch: 100
  n_episode: 2
  n_way: 15
  n_shot: 1
  n_query: 9
  deterministic: True  # whether set images in dataset to be deterministic in each epoch
val_set_args:
  root: /srv/home/zxu444/datasets/domainNet/sketch_split
  split: meta-val
  size: 224           # added for ViT
  transform: clip
  n_batch: 20
  n_episode: 2
  n_way: 15
  n_shot: 1
  n_query: 10
  deterministic: True  # whether set images in dataset to be deterministic in each epoch


encoder: clip_ViT-B32

# path: ./save/task_samples/task5000/meta-mini-imagenet_ViT-B32_fs-centroid_5y25s_1000size
# path: ./save/clip/meta-mini-imagenet_RN50_fs-centroid_5y1s_finetune_clip
# path: ./save/mini-imagenet/Mm_trend/meta-mini-imagenet_ViT-B32_fs-centroid_15y4s_600m_800M

path: ./save/clip/mini-imagenet/Mm_trend/meta-mini-imagenet_clip_ViT-B32_fs-centroid_15y2s18q_300m_100M
ckpt: epoch-5.pth
start_epoch_from: 5

classifier: fs-centroid
classifier_args:
  temp: 10.
  learn_temp: True

optimizer: sgd
optimizer_args:
  lr: 1.e-5 # 0.001
  momentum: 0.9
  weight_decay: 5.e-6


########### M,m trend
save_path: ./save/clip/domain-net/mixed_mini_start_from_5


save_epoch: 1
V: 1
n_epochs: 5

