dataset: meta-domain-net
test_set_args:
  root: /srv/home/zxu444/datasets/domainNet/sketch_split
  split: meta-test
  size: 224                 
  transform: clip
  n_batch: 150
  n_episode: 1
  n_way: 15
  n_shot: 5
  n_query: 15


# encoder: ViT-B32
encoder: RN50
# path: ./save/clip/domain-net/Mm_trend/meta-domain-net_ViT-B32_fs-centroid_15y1s_150m_200M
path: ./save/clip/domain-net/Mm_trend/meta-domain-net_RN50_fs-centroid_15y1s_150m_200M

# path: ./save/tiered-imagenet/original

ckpt: max-va.pth
# ckpt: epoch-last.pth


classifier: fs-centroid
classifier_args:
  temp: 10.

V: 1
n_epochs: 10
