dataset: meta-tiered-imagenet
test_set_args:
  split: meta-test
  size: 224                
  transform: make_classification_eval_transform
  n_batch: 150
  n_episode: 1
  n_way: 15
  n_shot: 5
  n_query: 15


# encoder: torchvision_vit_b_32
# path: ./save/torchvision/tiered-imagenet/Mm_trend/meta-tiered-imagenet_torchvision_vit_b_32_fs-centroid_15y1s_150m_200M

encoder: torchvision_RN50
path: ./save/torchvision/tiered-imagenet/Mm_trend/meta-tiered-imagenet_torchvision_RN50_fs-centroid_15y1s_150m_200M

ckpt: max-va.pth
# ckpt: epoch-last.pth


classifier: fs-centroid
classifier_args:
  temp: 10.

V: 1
n_epochs: 10